from datetime import date

from src.models import DigestItem, Paper
from src.renderers import render_html, render_text


def make_item(rank: int, llm_generated: bool = True, authors=None) -> DigestItem:
    paper = Paper(
        paper_id="2508.01234",
        title="A Great Paper on RAG",
        abstract="We propose a new method.",
        authors=authors or ["Alice", "Bob", "Carol", "Dave"],
        published_at=date(2026, 8, 10),
        upvotes=42,
        hf_url="https://huggingface.co/papers/2508.01234",
        arxiv_url="https://arxiv.org/abs/2508.01234",
    )
    return DigestItem(
        paper=paper,
        rank=rank,
        summary="This is the summary.",
        relevance_note="Matches your RAG interest.",
        matched_areas=["Retrieval-Augmented Generation"],
        llm_generated=llm_generated,
    )


def test_render_html_includes_core_fields():
    items = [make_item(1)]
    html = render_html(items, "2026-W32", generated_on=date(2026, 8, 18))

    assert "2026-W32" in html
    assert "A Great Paper on RAG" in html
    assert "https://huggingface.co/papers/2508.01234" in html
    assert "https://arxiv.org/abs/2508.01234" in html
    assert "Matches your RAG interest." in html
    assert "<style>" not in html
    assert "<table" in html


def test_render_html_truncates_authors_to_three_plus_et_al():
    items = [make_item(1)]
    html = render_html(items, "2026-W32")
    assert "Alice, Bob, Carol et al." in html
    assert "Dave" not in html


def test_render_html_footer_notes_extracted_summaries():
    items = [make_item(1, llm_generated=False)]
    html = render_html(items, "2026-W32")
    assert "extracted directly from abstracts" in html


def test_render_html_footer_notes_llm_generated_when_all_llm():
    items = [make_item(1, llm_generated=True)]
    html = render_html(items, "2026-W32")
    assert "generated by Gemini" in html


def test_render_text_contains_links_and_summary():
    items = [make_item(1)]
    text = render_text(items, "2026-W32")
    assert "2026-W32" in text
    assert "https://huggingface.co/papers/2508.01234" in text
    assert "This is the summary." in text
    assert "Matches your RAG interest." in text
