"""HTML (table-based, inline-CSS) and plain-text renderers for the digest email."""

from __future__ import annotations

from datetime import date
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, select_autoescape

from src.models import DigestItem

TEMPLATE_DIR = Path(__file__).parent / "templates"

_env = Environment(
    loader=FileSystemLoader(str(TEMPLATE_DIR)),
    autoescape=select_autoescape(["html"]),
)


def _format_authors(authors: list[str]) -> str:
    if len(authors) <= 3:
        return ", ".join(authors)
    return ", ".join(authors[:3]) + " et al."


def render_html(items: list[DigestItem], week: str, generated_on: date | None = None) -> str:
    template = _env.get_template("digest.html.j2")
    generated_on = generated_on or date.today()
    all_llm_generated = bool(items) and all(item.llm_generated for item in items)
    return template.render(
        items=items,
        week=week,
        generated_on=generated_on.isoformat(),
        paper_count=len(items),
        all_llm_generated=all_llm_generated,
        format_authors=_format_authors,
    )


def render_text(items: list[DigestItem], week: str) -> str:
    lines = [f"Weekly Top {len(items)} Research Papers Digest - {week}", ""]
    for item in items:
        lines.append(f"{item.rank}. {item.paper.title}")
        lines.append(f"   HF: {item.paper.hf_url}")
        lines.append(f"   arXiv: {item.paper.arxiv_url}")
        lines.append(f"   Authors: {_format_authors(item.paper.authors)}")
        lines.append(f"   Upvotes: {item.paper.upvotes}")
        if item.matched_areas:
            lines.append(f"   Areas: {', '.join(item.matched_areas)}")
        lines.append(f"   Summary: {item.summary}")
        lines.append(f"   Why it matters: {item.relevance_note}")
        lines.append("")

    source_note = (
        "All summaries generated by Gemini."
        if items and all(item.llm_generated for item in items)
        else "Some or all summaries were extracted from abstracts (LLM unavailable this run)."
    )
    lines.append(source_note)
    lines.append("Source: Hugging Face Daily Papers (https://huggingface.co/papers)")

    return "\n".join(lines)
